#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Mar  9 15:14:38 2017

@author: katiemapes
"""

"""Nearest Neighbor Model"""

import math
import operator 


def euclideanDistance(instance1, instance2, length):
    distance = 0
    for x in range(length):
        distance += pow((instance1[x] - instance2[x]), 2)
    return math.sqrt(distance)



def getNeighbors(trainingSet, testInstance, k):
    distances = []
    length = len(testInstance)-1
    for x in range(len(trainingSet)):
        dist = euclideanDistance(testInstance, trainingSet[x], length)
        distances.append((trainingSet[x], dist))
    distances.sort(key=operator.itemgetter(1))
    neighbors = []
    for x in range(k):
        neighbors.append(distances[x][0])
    return neighbors
 
def test_run():

    trainSet = [[2, 2, 'a'], [4, 4, 'b']]
    testInstance = [5, 5]
    k = 2
    neighbors = getNeighbors(trainSet, testInstance, k)
    print(neighbors)
    

if __name__ == "__main__":
    test_run()

